name: Release Build

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller==6.13.0

    - name: Build exe
      run: |
        pyinstaller --onefile --windowed --name=main --add-data "src;src" main.py

    files: |
      dist/main.exe